option("cpp", {default = "20"})
target("unordered_dense")
    set_kind("moduleonly")
    set_languages("c++" .. (get_config("cpp") or "20"))
    add_headerfiles("include/(**.h)")
    add_includedirs("include")
    add_files("src/ankerl.unordered_dense.cpp", {public = true})
    add_options("cpp")
    set_policy("build.c++.modules", true)

target("example")
    set_kind("binary")
    set_languages("c++" .. (get_config("cpp") or "20"))
    add_options("cpp")
    add_deps("unordered_dense")
    add_defines("MODULES")
    add_files("example/main.cpp")
    set_policy("build.c++.modules", true)
