#include <ankerl/unordered_dense.h>

#include <app/doctest.h>

#include <cstddef> // for size_t
#include <cstdint> // for uint64_t, uint8_t
#include <cstring> // for memcpy
#include <string>  // for string, basic_string
#include <vector>  // for vector

// What the hash actually computes, pinned.
//
// Every other test here asks whether the *map* is right, and the map is right whatever the hash
// returns -- so a changed hash is invisible to all of them. That is not hypothetical: a mutation
// sweep found that any constant in the secret, any mixing step and most of the length arithmetic
// can be changed with the whole suite staying green. These are the values, so that a change to the
// hash has to be a decision rather than an accident.
//
// Two things follow from that.
//
// This is not a promise that the values never change. Replacing wyhash with something faster is a
// legitimate thing to do, and when it happens this file is *expected* to go red. Regenerate it
// then: the inputs below are generated by the two loops in the test, so printing the new values is
// a few lines, and the review question is "did we mean to change the hash", which is exactly the
// question this exists to raise.
//
// The values are little-endian only, and the header says so where the reads are defined: it copies
// bytes straight into a uint64_t and does not swap them. Every CI leg is little-endian, and rather
// than bake a wrong expectation for a machine we do not test on, the check steps aside there.

namespace {

// True when this machine is one the golden values were taken on, and says so in the test log when
// it is not -- rather than passing silently, which looks the same as having checked.
[[nodiscard]] auto skip_on_big_endian() -> bool {
    std::uint32_t const one = 1;
    std::uint8_t first{};
    std::memcpy(&first, &one, 1);
    if (1 == first) {
        return false;
    }
    MESSAGE("skipped: these values are little-endian, and so is the hash");
    return true;
}

// Deterministic, and not all-zero or all-one: a buffer of equal bytes hides a mutated offset,
// because every byte it could read instead is the same byte.
[[nodiscard]] auto pattern(std::size_t size) -> std::vector<std::uint8_t> {
    auto data = std::vector<std::uint8_t>(size);
    for (std::size_t i = 0; i < size; ++i) {
        data[i] = static_cast<std::uint8_t>(i * 7 + 1);
    }
    return data;
}

} // namespace

// One length per branch of wyhash::hash and both sides of every boundary it switches on: 3/4 (the
// 3-byte read), 7/8 (the 4-byte pair), 16/17 (the 8-byte pair vs the loop), 48/49 (the three-lane
// loop) and 96/97 (the six-lane one). A mutated bound moves one of these onto the wrong branch.
//
// The loops need more than their entry conditions, though: a `>` that became `>=` only differs on
// the iteration where the counter lands exactly on the bound, so there are lengths here that leave
// it at 17 after the 48-byte loop (65) and at 96 after the 96-byte one (192, 289).
TEST_CASE("wyhash_golden_values_by_length") {
    if (skip_on_big_endian()) {
        return;
    }

    // Sized by its contents: adding a length here must not also mean bumping a count.
    static constexpr std::pair<std::size_t, std::uint64_t> expected[] = {
        {0, UINT64_C(0x42bc986dc5eec4d3)},   {1, UINT64_C(0x3e73bcceee051a90)},   {2, UINT64_C(0xabb36df2a05cdd96)},
        {3, UINT64_C(0x737b3594dbad4615)},   {4, UINT64_C(0x06959e50533f44b2)},   {5, UINT64_C(0x36e18d353c41722a)},
        {7, UINT64_C(0xc3e479040f170b82)},   {8, UINT64_C(0xd7517cd74fe903fb)},   {9, UINT64_C(0x7050188f7743ca56)},
        {15, UINT64_C(0xb4f9a728274096d7)},  {16, UINT64_C(0xce6a868a78a46c73)},  {17, UINT64_C(0xab9f0d72fd62acbb)},
        {24, UINT64_C(0xaf048c621425ee78)},  {32, UINT64_C(0x46f297d4bd07d149)},  {48, UINT64_C(0x9e97709342df6b56)},
        {49, UINT64_C(0x3b846738927f6274)},  {64, UINT64_C(0xd4a468aebbe74bfa)},  {65, UINT64_C(0x68624a1222e1898b)},
        {96, UINT64_C(0x2d9d003ab847fe53)},  {97, UINT64_C(0x97ef6fc060548571)},  {128, UINT64_C(0x04c929c0de5c5ada)},
        {192, UINT64_C(0x188b2a6bd5264944)}, {193, UINT64_C(0x11ff8ae436691f52)}, {200, UINT64_C(0xc0895d26f8d2d90f)},
        {289, UINT64_C(0xede2975ce774d7e7)}, {300, UINT64_C(0xb8446c7b09ba427b)}, {512, UINT64_C(0x2c274db7d27dc42b)},
    };

    auto const data = pattern(512);
    for (auto const& entry : expected) {
        // Copied out of the structured binding rather than used directly: doctest's INFO builds a
        // lambda around what it is given, and capturing a structured binding is C++20.
        auto const len = entry.first;
        auto const want = entry.second;
        INFO("length ", len);
        REQUIRE(ankerl::unordered_dense::detail::wyhash::hash(data.data(), len) == want);
    }
}

// A hash of the same bytes has to be the same wherever the bytes came from -- and on a 32 bit
// target `mum` takes its long-hand branch instead of __uint128_t, so this is also what says the two
// multiplications agree.
TEST_CASE("wyhash_reads_only_the_bytes_it_was_given") {
    if (skip_on_big_endian()) {
        return;
    }
    auto const data = pattern(512);
    for (std::size_t len = 0; len <= 200; ++len) {
        INFO("length ", len);
        // The same prefix inside a larger buffer, and inside one sized exactly to it. A read that
        // runs past the end is the same value in the first and something else in the second.
        auto const exact = std::vector<std::uint8_t>(data.begin(), data.begin() + static_cast<long>(len));
        REQUIRE(ankerl::unordered_dense::detail::wyhash::hash(data.data(), len) ==
                ankerl::unordered_dense::detail::wyhash::hash(exact.data(), len));
    }
}

TEST_CASE("wyhash_golden_values_for_the_integer_overload") {
    // No endianness in this one: it takes a uint64_t, not bytes.
    static constexpr std::pair<std::uint64_t, std::uint64_t> expected[] = {
        {UINT64_C(0), UINT64_C(0x0000000000000000)},
        {UINT64_C(1), UINT64_C(0x9e3779b97f4a7c15)},
        {UINT64_C(2), UINT64_C(0x3c6ef372fe94f82b)},
        {UINT64_C(42), UINT64_C(0xf519f86ee2385b6b)},
        {UINT64_C(0x0123456789abcdef), UINT64_C(0x0c27a443d5ff218e)},
        {UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff)},
    };
    for (auto const& entry : expected) {
        auto const input = entry.first;
        auto const want = entry.second;
        INFO("input ", input);
        REQUIRE(ankerl::unordered_dense::detail::wyhash::hash(input) == want);
    }
}

// The same values again through the public hashers, which is what a user's map actually calls.
TEST_CASE("public_hashers_golden_values") {
    if (skip_on_big_endian()) {
        return;
    }
    REQUIRE(ankerl::unordered_dense::hash<std::string>{}("") == UINT64_C(0x42bc986dc5eec4d3));
    REQUIRE(ankerl::unordered_dense::hash<std::string>{}("a") == UINT64_C(0x6cf84e5a2465e867));
    REQUIRE(ankerl::unordered_dense::hash<std::string>{}("hello") == UINT64_C(0x8a530a885be59d42));
    REQUIRE(ankerl::unordered_dense::hash<std::string>{}("hello world, this is a longer key") == UINT64_C(0x5ff2678617d5e07b));
    REQUIRE(ankerl::unordered_dense::hash<std::string>{}(std::string(200, 'x')) == UINT64_C(0xc85c216c50379a39));

    // A string_view of the same bytes has to agree with the string, or a transparent lookup finds
    // nothing.
    REQUIRE(ankerl::unordered_dense::hash<std::string_view>{}("hello") ==
            ankerl::unordered_dense::hash<std::string>{}("hello"));

    REQUIRE(ankerl::unordered_dense::hash<std::uint64_t>{}(42) == UINT64_C(0xf519f86ee2385b6b));
    REQUIRE(ankerl::unordered_dense::hash<int>{}(42) == UINT64_C(0xf519f86ee2385b6b));
}
