#include <ankerl/unordered_dense.h>

#include <app/doctest.h>

#include <cstdint>     // for uint64_t
#include <limits>      // for numeric_limits
#include <type_traits> // for is_signed_v

// Every built-in integer type gets its own hash<T> specialization, generated by a macro, and the
// list of them is seventeen lines that nothing was checking. A deletion sweep removed each line in
// turn and the whole suite stayed green, because losing one is invisible unless you look: hash<T>
// falls back to the primary template, which forwards to std::hash<T> and is *not* marked
// avalanching. So the two things that change are exactly the two things asserted here.
//
// This file used to hold a single empty test case and a "TODO make hash generic?" comment, which
// is what that TODO was asking for.

namespace {

// What the specialization promises: the value widened to 64 bits and put through wyhash. Signed
// types sign-extend on the way, which is the cast the macro itself performs -- writing the same
// cast here rather than a mask is deliberate, so a change to that cast shows up as a failure.
template <typename T>
void require_hashes_as_wyhash_of(T value) {
    auto const expected = ankerl::unordered_dense::detail::wyhash::hash(static_cast<std::uint64_t>(value));
    REQUIRE(ankerl::unordered_dense::hash<T>{}(value) == expected);
}

// Interesting values for whichever type this is: the ends of its range and something in between.
// The extremes are what tell a sign-extending cast from a zero-extending one.
template <typename T>
void require_specialization_holds() {
    // The marker is the other half of the specialization. Without it the table stops trusting the
    // hash and mixes it again, which is a behaviour change no value comparison can see.
    static_assert(ankerl::unordered_dense::hash_is_avalanching_v<ankerl::unordered_dense::hash<T>>,
                  "a scalar hash has to be avalanching, or the table pays to mix it a second time");

    require_hashes_as_wyhash_of<T>(static_cast<T>(0));
    require_hashes_as_wyhash_of<T>(static_cast<T>(1));
    require_hashes_as_wyhash_of<T>((std::numeric_limits<T>::max)());
    require_hashes_as_wyhash_of<T>((std::numeric_limits<T>::min)());
}

} // namespace

TEST_CASE_TEMPLATE("hash_of_a_scalar_is_the_wyhash_of_its_widened_value",
                   T,
                   bool,
                   char,
                   signed char,
                   unsigned char,
                   char16_t,
                   char32_t,
                   wchar_t,
                   short,
                   unsigned short,
                   int,
                   unsigned int,
                   long,
                   long long,
                   unsigned long,
                   unsigned long long) {
    require_specialization_holds<T>();
}

#if ANKERL_UNORDERED_DENSE_CPP_VERSION >= 202002L && defined(__cpp_char8_t)
// Guarded exactly as the specialization is, so this leg only exists where that one does.
TEST_CASE("hash_of_char8_t_is_the_wyhash_of_its_widened_value") {
    require_specialization_holds<char8_t>();
}
#endif

// The distinction the specializations exist for: a type that has one is avalanching and hashes to
// the wyhash of its value, and a type that falls through to the primary template is neither. If
// these two ever answer the same, the check above has stopped being able to fail.
namespace {

struct not_specialized {
    int value = 0;
};

} // namespace

template <>
struct std::hash<not_specialized> {
    auto operator()(not_specialized const& n) const noexcept -> std::size_t {
        return static_cast<std::size_t>(n.value);
    }
};

TEST_CASE("a_type_without_a_specialization_is_not_avalanching") {
    static_assert(!ankerl::unordered_dense::hash_is_avalanching_v<ankerl::unordered_dense::hash<not_specialized>>,
                  "the primary template forwards to std::hash and must not claim to avalanche");
    static_assert(ankerl::unordered_dense::hash_is_avalanching_v<ankerl::unordered_dense::hash<int>>,
                  "... while a specialized one does, which is what makes the negative above meaningful");

    REQUIRE(ankerl::unordered_dense::hash<not_specialized>{}(not_specialized{7}) == 7);
}
